name: Angular Application

env:
  DOCKER_USERNAME: nologin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: Set Node 10
        uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: 'npm'

      - name: CI
        run: npm ci

      - name: Lint avec node
        run: npm run lint

      - name: build avec Node
        run: npm run build

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/polytech2024
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rg.fr-par.scw.cloud/polytech-2024/mgagneur/frontend:v2.0
